/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package eu.stratosphere.test.testPlan;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"eu.stratosphere.test.testPlan\",\"fields\":[{\"name\":\"o_orderkey\",\"type\":\"int\"},{\"name\":\"o_custkey\",\"type\":\"int\"},{\"name\":\"o_orderstatus\",\"type\":\"string\"},{\"name\":\"o_totalprice\",\"type\":\"float\"},{\"name\":\"o_orderdate\",\"type\":\"string\"},{\"name\":\"o_orderpriority\",\"type\":\"string\"},{\"name\":\"o_clerk\",\"type\":\"string\"},{\"name\":\"o_shipproprity\",\"type\":\"int\"},{\"name\":\"o_comment\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int o_orderkey;
  @Deprecated public int o_custkey;
  @Deprecated public java.lang.CharSequence o_orderstatus;
  @Deprecated public float o_totalprice;
  @Deprecated public java.lang.CharSequence o_orderdate;
  @Deprecated public java.lang.CharSequence o_orderpriority;
  @Deprecated public java.lang.CharSequence o_clerk;
  @Deprecated public int o_shipproprity;
  @Deprecated public java.lang.CharSequence o_comment;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public Order() {}

  /**
   * All-args constructor.
   */
  public Order(java.lang.Integer o_orderkey, java.lang.Integer o_custkey, java.lang.CharSequence o_orderstatus, java.lang.Float o_totalprice, java.lang.CharSequence o_orderdate, java.lang.CharSequence o_orderpriority, java.lang.CharSequence o_clerk, java.lang.Integer o_shipproprity, java.lang.CharSequence o_comment) {
    this.o_orderkey = o_orderkey;
    this.o_custkey = o_custkey;
    this.o_orderstatus = o_orderstatus;
    this.o_totalprice = o_totalprice;
    this.o_orderdate = o_orderdate;
    this.o_orderpriority = o_orderpriority;
    this.o_clerk = o_clerk;
    this.o_shipproprity = o_shipproprity;
    this.o_comment = o_comment;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return o_orderkey;
    case 1: return o_custkey;
    case 2: return o_orderstatus;
    case 3: return o_totalprice;
    case 4: return o_orderdate;
    case 5: return o_orderpriority;
    case 6: return o_clerk;
    case 7: return o_shipproprity;
    case 8: return o_comment;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: o_orderkey = (java.lang.Integer)value$; break;
    case 1: o_custkey = (java.lang.Integer)value$; break;
    case 2: o_orderstatus = (java.lang.CharSequence)value$; break;
    case 3: o_totalprice = (java.lang.Float)value$; break;
    case 4: o_orderdate = (java.lang.CharSequence)value$; break;
    case 5: o_orderpriority = (java.lang.CharSequence)value$; break;
    case 6: o_clerk = (java.lang.CharSequence)value$; break;
    case 7: o_shipproprity = (java.lang.Integer)value$; break;
    case 8: o_comment = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'o_orderkey' field.
   */
  public java.lang.Integer getOOrderkey() {
    return o_orderkey;
  }

  /**
   * Sets the value of the 'o_orderkey' field.
   * @param value the value to set.
   */
  public void setOOrderkey(java.lang.Integer value) {
    this.o_orderkey = value;
  }

  /**
   * Gets the value of the 'o_custkey' field.
   */
  public java.lang.Integer getOCustkey() {
    return o_custkey;
  }

  /**
   * Sets the value of the 'o_custkey' field.
   * @param value the value to set.
   */
  public void setOCustkey(java.lang.Integer value) {
    this.o_custkey = value;
  }

  /**
   * Gets the value of the 'o_orderstatus' field.
   */
  public java.lang.CharSequence getOOrderstatus() {
    return o_orderstatus;
  }

  /**
   * Sets the value of the 'o_orderstatus' field.
   * @param value the value to set.
   */
  public void setOOrderstatus(java.lang.CharSequence value) {
    this.o_orderstatus = value;
  }

  /**
   * Gets the value of the 'o_totalprice' field.
   */
  public java.lang.Float getOTotalprice() {
    return o_totalprice;
  }

  /**
   * Sets the value of the 'o_totalprice' field.
   * @param value the value to set.
   */
  public void setOTotalprice(java.lang.Float value) {
    this.o_totalprice = value;
  }

  /**
   * Gets the value of the 'o_orderdate' field.
   */
  public java.lang.CharSequence getOOrderdate() {
    return o_orderdate;
  }

  /**
   * Sets the value of the 'o_orderdate' field.
   * @param value the value to set.
   */
  public void setOOrderdate(java.lang.CharSequence value) {
    this.o_orderdate = value;
  }

  /**
   * Gets the value of the 'o_orderpriority' field.
   */
  public java.lang.CharSequence getOOrderpriority() {
    return o_orderpriority;
  }

  /**
   * Sets the value of the 'o_orderpriority' field.
   * @param value the value to set.
   */
  public void setOOrderpriority(java.lang.CharSequence value) {
    this.o_orderpriority = value;
  }

  /**
   * Gets the value of the 'o_clerk' field.
   */
  public java.lang.CharSequence getOClerk() {
    return o_clerk;
  }

  /**
   * Sets the value of the 'o_clerk' field.
   * @param value the value to set.
   */
  public void setOClerk(java.lang.CharSequence value) {
    this.o_clerk = value;
  }

  /**
   * Gets the value of the 'o_shipproprity' field.
   */
  public java.lang.Integer getOShipproprity() {
    return o_shipproprity;
  }

  /**
   * Sets the value of the 'o_shipproprity' field.
   * @param value the value to set.
   */
  public void setOShipproprity(java.lang.Integer value) {
    this.o_shipproprity = value;
  }

  /**
   * Gets the value of the 'o_comment' field.
   */
  public java.lang.CharSequence getOComment() {
    return o_comment;
  }

  /**
   * Sets the value of the 'o_comment' field.
   * @param value the value to set.
   */
  public void setOComment(java.lang.CharSequence value) {
    this.o_comment = value;
  }

  /** Creates a new Order RecordBuilder */
  public static eu.stratosphere.test.testPlan.Order.Builder newBuilder() {
    return new eu.stratosphere.test.testPlan.Order.Builder();
  }
  
  /** Creates a new Order RecordBuilder by copying an existing Builder */
  public static eu.stratosphere.test.testPlan.Order.Builder newBuilder(eu.stratosphere.test.testPlan.Order.Builder other) {
    return new eu.stratosphere.test.testPlan.Order.Builder(other);
  }
  
  /** Creates a new Order RecordBuilder by copying an existing Order instance */
  public static eu.stratosphere.test.testPlan.Order.Builder newBuilder(eu.stratosphere.test.testPlan.Order other) {
    return new eu.stratosphere.test.testPlan.Order.Builder(other);
  }
  
  /**
   * RecordBuilder for Order instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    private int o_orderkey;
    private int o_custkey;
    private java.lang.CharSequence o_orderstatus;
    private float o_totalprice;
    private java.lang.CharSequence o_orderdate;
    private java.lang.CharSequence o_orderpriority;
    private java.lang.CharSequence o_clerk;
    private int o_shipproprity;
    private java.lang.CharSequence o_comment;

    /** Creates a new Builder */
    private Builder() {
      super(eu.stratosphere.test.testPlan.Order.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(eu.stratosphere.test.testPlan.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.o_orderkey)) {
        this.o_orderkey = data().deepCopy(fields()[0].schema(), other.o_orderkey);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.o_custkey)) {
        this.o_custkey = data().deepCopy(fields()[1].schema(), other.o_custkey);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.o_orderstatus)) {
        this.o_orderstatus = data().deepCopy(fields()[2].schema(), other.o_orderstatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.o_totalprice)) {
        this.o_totalprice = data().deepCopy(fields()[3].schema(), other.o_totalprice);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.o_orderdate)) {
        this.o_orderdate = data().deepCopy(fields()[4].schema(), other.o_orderdate);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.o_orderpriority)) {
        this.o_orderpriority = data().deepCopy(fields()[5].schema(), other.o_orderpriority);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.o_clerk)) {
        this.o_clerk = data().deepCopy(fields()[6].schema(), other.o_clerk);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.o_shipproprity)) {
        this.o_shipproprity = data().deepCopy(fields()[7].schema(), other.o_shipproprity);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.o_comment)) {
        this.o_comment = data().deepCopy(fields()[8].schema(), other.o_comment);
        fieldSetFlags()[8] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Order instance */
    private Builder(eu.stratosphere.test.testPlan.Order other) {
            super(eu.stratosphere.test.testPlan.Order.SCHEMA$);
      if (isValidValue(fields()[0], other.o_orderkey)) {
        this.o_orderkey = data().deepCopy(fields()[0].schema(), other.o_orderkey);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.o_custkey)) {
        this.o_custkey = data().deepCopy(fields()[1].schema(), other.o_custkey);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.o_orderstatus)) {
        this.o_orderstatus = data().deepCopy(fields()[2].schema(), other.o_orderstatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.o_totalprice)) {
        this.o_totalprice = data().deepCopy(fields()[3].schema(), other.o_totalprice);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.o_orderdate)) {
        this.o_orderdate = data().deepCopy(fields()[4].schema(), other.o_orderdate);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.o_orderpriority)) {
        this.o_orderpriority = data().deepCopy(fields()[5].schema(), other.o_orderpriority);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.o_clerk)) {
        this.o_clerk = data().deepCopy(fields()[6].schema(), other.o_clerk);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.o_shipproprity)) {
        this.o_shipproprity = data().deepCopy(fields()[7].schema(), other.o_shipproprity);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.o_comment)) {
        this.o_comment = data().deepCopy(fields()[8].schema(), other.o_comment);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'o_orderkey' field */
    public java.lang.Integer getOOrderkey() {
      return o_orderkey;
    }
    
    /** Sets the value of the 'o_orderkey' field */
    public eu.stratosphere.test.testPlan.Order.Builder setOOrderkey(int value) {
      validate(fields()[0], value);
      this.o_orderkey = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'o_orderkey' field has been set */
    public boolean hasOOrderkey() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'o_orderkey' field */
    public eu.stratosphere.test.testPlan.Order.Builder clearOOrderkey() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'o_custkey' field */
    public java.lang.Integer getOCustkey() {
      return o_custkey;
    }
    
    /** Sets the value of the 'o_custkey' field */
    public eu.stratosphere.test.testPlan.Order.Builder setOCustkey(int value) {
      validate(fields()[1], value);
      this.o_custkey = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'o_custkey' field has been set */
    public boolean hasOCustkey() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'o_custkey' field */
    public eu.stratosphere.test.testPlan.Order.Builder clearOCustkey() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'o_orderstatus' field */
    public java.lang.CharSequence getOOrderstatus() {
      return o_orderstatus;
    }
    
    /** Sets the value of the 'o_orderstatus' field */
    public eu.stratosphere.test.testPlan.Order.Builder setOOrderstatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.o_orderstatus = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'o_orderstatus' field has been set */
    public boolean hasOOrderstatus() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'o_orderstatus' field */
    public eu.stratosphere.test.testPlan.Order.Builder clearOOrderstatus() {
      o_orderstatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'o_totalprice' field */
    public java.lang.Float getOTotalprice() {
      return o_totalprice;
    }
    
    /** Sets the value of the 'o_totalprice' field */
    public eu.stratosphere.test.testPlan.Order.Builder setOTotalprice(float value) {
      validate(fields()[3], value);
      this.o_totalprice = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'o_totalprice' field has been set */
    public boolean hasOTotalprice() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'o_totalprice' field */
    public eu.stratosphere.test.testPlan.Order.Builder clearOTotalprice() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'o_orderdate' field */
    public java.lang.CharSequence getOOrderdate() {
      return o_orderdate;
    }
    
    /** Sets the value of the 'o_orderdate' field */
    public eu.stratosphere.test.testPlan.Order.Builder setOOrderdate(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.o_orderdate = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'o_orderdate' field has been set */
    public boolean hasOOrderdate() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'o_orderdate' field */
    public eu.stratosphere.test.testPlan.Order.Builder clearOOrderdate() {
      o_orderdate = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'o_orderpriority' field */
    public java.lang.CharSequence getOOrderpriority() {
      return o_orderpriority;
    }
    
    /** Sets the value of the 'o_orderpriority' field */
    public eu.stratosphere.test.testPlan.Order.Builder setOOrderpriority(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.o_orderpriority = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'o_orderpriority' field has been set */
    public boolean hasOOrderpriority() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'o_orderpriority' field */
    public eu.stratosphere.test.testPlan.Order.Builder clearOOrderpriority() {
      o_orderpriority = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'o_clerk' field */
    public java.lang.CharSequence getOClerk() {
      return o_clerk;
    }
    
    /** Sets the value of the 'o_clerk' field */
    public eu.stratosphere.test.testPlan.Order.Builder setOClerk(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.o_clerk = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'o_clerk' field has been set */
    public boolean hasOClerk() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'o_clerk' field */
    public eu.stratosphere.test.testPlan.Order.Builder clearOClerk() {
      o_clerk = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'o_shipproprity' field */
    public java.lang.Integer getOShipproprity() {
      return o_shipproprity;
    }
    
    /** Sets the value of the 'o_shipproprity' field */
    public eu.stratosphere.test.testPlan.Order.Builder setOShipproprity(int value) {
      validate(fields()[7], value);
      this.o_shipproprity = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'o_shipproprity' field has been set */
    public boolean hasOShipproprity() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'o_shipproprity' field */
    public eu.stratosphere.test.testPlan.Order.Builder clearOShipproprity() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'o_comment' field */
    public java.lang.CharSequence getOComment() {
      return o_comment;
    }
    
    /** Sets the value of the 'o_comment' field */
    public eu.stratosphere.test.testPlan.Order.Builder setOComment(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.o_comment = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'o_comment' field has been set */
    public boolean hasOComment() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'o_comment' field */
    public eu.stratosphere.test.testPlan.Order.Builder clearOComment() {
      o_comment = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public Order build() {
      try {
        Order record = new Order();
        record.o_orderkey = fieldSetFlags()[0] ? this.o_orderkey : (java.lang.Integer) defaultValue(fields()[0]);
        record.o_custkey = fieldSetFlags()[1] ? this.o_custkey : (java.lang.Integer) defaultValue(fields()[1]);
        record.o_orderstatus = fieldSetFlags()[2] ? this.o_orderstatus : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.o_totalprice = fieldSetFlags()[3] ? this.o_totalprice : (java.lang.Float) defaultValue(fields()[3]);
        record.o_orderdate = fieldSetFlags()[4] ? this.o_orderdate : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.o_orderpriority = fieldSetFlags()[5] ? this.o_orderpriority : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.o_clerk = fieldSetFlags()[6] ? this.o_clerk : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.o_shipproprity = fieldSetFlags()[7] ? this.o_shipproprity : (java.lang.Integer) defaultValue(fields()[7]);
        record.o_comment = fieldSetFlags()[8] ? this.o_comment : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
